---
# tasks file for azurerm_resource_group

- name: Create resource group
  azure_rm_resourcegroup:
    name: "{{ rg_name }}"
    location: "{{ location }}"
    state: present
  register: rg
  when: not delete and not delete_rg

- name: Get rg Info
  azure_rm_resourcegroup_facts:
      name: "{{rg_name}}" # not required. Limit results to a specific resource group.

- name: Delete resource group
  azure_rm_resourcegroup:
    name: "{{ rg_name }}"
    location: "{{ location }}"
    state: absent
  when: delete or delete_rg

