---
# tasks file for azurerm_virtualnetwork

- name: Create Virtual Network
  azure_rm_virtualnetwork:
    name: "{{ vnet_name }}"
    resource_group: "{{ ansible_facts.azure_resourcegroups[0].name }}"
    address_prefixes_cidr: "{{ address_prefixes_cidr }}"
    append_tags: yes
    location: "{{ ansible_facts.azure_resourcegroups[0].location }}"
    state: present
  when: not delete and not delete_vnet

- name: Register vnet facts
  azure_rm_virtualnetwork_facts:
      name: "{{vnet_name}}" # not required. Only show results for a specific security group.
      resource_group: "{{ansible_facts.azure_resourcegroups[0].name}}" # not required. Limit results by resource group. Required when filtering by name.

- name: Delete Virtual Network
  azure_rm_virtualnetwork:
    name: "{{ vnet_name }}"
    resource_group: "{{ ansible_facts.azure_resourcegroups[0].name }}"
    address_prefixes_cidr: "{{ address_prefixes_cidr }}"
    append_tags: yes
    location: "{{ ansible_facts.azure_resourcegroups[0].location }}"
    state: absent
  when: delete or delete_vnet
