---

- src: https://github.com/jmarfr/ansible-arm-vnet
- src: https://github.com/jmarfr/ansible-arm-subnet
- src: https://github.com/jmarfr/ansible-arm-vm
- src: https://github.com/jmarfr/ansible-arm-rg
- src: https://github.com/jmarfr/ansible-arm-lb
