---
# tasks file for azurerm_subnets

- name: Create subnets
  azure_rm_subnet:
      resource_group: "{{ ansible_facts.azure_resourcegroups[0].name }}" # required. Name of resource group.
      virtual_network_name: "{{ansible_facts.azure_virtualnetworks[0].name}}" # required. Name of an existing virtual network with which the subnet is or will be associated.
      name: "{{item.name}}" # required. Name of the subnet.
      address_prefix_cidr: "{{item.cidr}}" # required. CIDR defining the IPv4 address space of the subnet. Must be valid within the context of the virtual network.
      state: present # not required. choices: absent;present. Assert the state of the subnet. Use 'present' to create or update a subnet and 'absent' to delete a subnet.
  with_items:
    - "{{subnets}}"