---
# tasks file for azurerm_virtualmachine
- name: Create availability set
  azure_rm_availabilityset:
    name: "{{ avset_name }}"
    location: "{{ location }}"
    resource_group: "{{ rg_name }}"
    sku: "Aligned"
    platform_fault_domain_count: "{{ avset_fault_domains }}"
    platform_update_domain_count: "{{ avset_update_domains }}"

- name: Create virtual machine
  azure_rm_virtualmachine:
    resource_group: "{{ rg_name }}"
    image:
      offer: "{{ vm_offer }}"
      publisher: "{{ vm_publisher }}"
      sku: "{{ vm_sku }}"
      version: "{{ vm_version }}"
    
    name: "{{ vm_name }}"
    availability_set: "{{ avset_name }}"
    public_ip_allocation: "{{ vm_pub_ip }}"
    managed_disk_type: "{{ vm_os_disk_type }}"
    allocated: true
    ssh_password_enabled: true
    remove_on_absent: all
    started: true
    state: present
    subnet_name: "{{ vm_subnet }}"
    admin_password: "{{ vm_admin_password }}"
    virtual_network_name: "{{ vnet_name }}"
    vm_size: "{{ vm_size }}"
    os_disk_size_gb: "{{ os_disk_size }}"
    admin_username: "{{ vm_admin_username }}"
    os_type: Linux
    os_disk_caching: ReadOnly
  register: arm_vm

- debug:
    var: arm_vm
    verbosity: 1

- name: Attach vm to LB
  azure_rm_networkinterface:
      resource_group: "{{ rg_name }}" # required. Name of a resource group where the network interface exists or will be created.
      name: "{{arm_vm.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces.0.name}}" # required. Name of the network interface.
      subnet_name: "{{ vm_subnet }}" # required. Name of an existing subnet within the specified virtual network. Required when creating a network interface,Use the C(virtual_network)'s resource group.
      virtual_network: "{{ vnet_name }}" # required. An existing virtual network with which the network interface will be associated. Required when creating a network interface.,It can be the virtual network's name.,Make sure your virtual network is in the same resource group as NIC when you give only the name.,It can be the virtual network's resource id.,It can be a dict which contains C(name) and C(resource_group) of the virtual network.
      ip_configurations: 
        - name: "{{ arm_vm.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces.0.properties.ipConfigurations.0.name }}"
          load_balancer_backend_address_pools:
            - name: "{{ lb_backend_pool_name }}"
              load_balancer: "{{ lb_name }}"
  when: lb_name != "None"

- name: "Delete vm {{ vm_name }}"
  azure_rm_virtualmachine:
    resource_group: "{{ rg_name }}"
    name: "{{ vm_name }}"
    state: absent
  when: delete or delete_vm

