---
# tasks file for azurerm_loadbalancer

- name: LB PubIP
  azure_rm_publicipaddress:
    name: "{{ lb_name }}-pip"
    resource_group: "{{ansible_facts.azure_resourcegroups.0.name}}"
    state: present
  register: pip


- name: Create LoadBalancer
  azure_rm_loadbalancer:
    resource_group: "{{ansible_facts.azure_resourcegroups.0.name}}"
    name: "{{ lb_name }}"
    load_balancing_rules:
      - name: lbrbalancingrule0
        frontend_ip_configuration: "frontendipconf0"
        backend_address_pool: backendaddrpool0
        frontend_port: 22
        backend_port: 22
        probe: probe_ssh
    probes:
      - name: probe_ssh
        fail_count: 3
        interval: 5
        port: 22
        protocol: Tcp
    sku: Basic
    backend_address_pools:
      - name: backendaddrpool0
    frontend_ip_configurations:
      - name: frontendipconf0
        public_ip_address: "{{pip.state.name}}"
    state: present